# Generated by Django 3.1.5 on 2021-01-06 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0002_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='boards', to='boards.board'),
        ),
    ]
