# Generated by Django 3.1.5 on 2021-01-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0003_auto_20210106_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
