# Generated by Django 3.1.5 on 2021-01-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boards', '0004_auto_20210109_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='board',
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='notes', to='boards.note'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
