# Generated by Django 3.1.5 on 2021-01-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210117_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='position',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
